var data = {lines:[
{"lineNum":"    1","line":"#pragma once"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include \"ast/node.hpp\""},
{"lineNum":"    4","line":""},
{"lineNum":"    5","line":"#include \"syntax/parser.hpp\""},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"namespace porpoise::ast {"},
{"lineNum":"    8","line":""},
{"lineNum":"    9","line":"class IdentifierExpression;"},
{"lineNum":"   10","line":""},
{"lineNum":"   11","line":"class ContinueStatement : public StmtBase<ContinueStatement> {"},
{"lineNum":"   12","line":"  public:"},
{"lineNum":"   13","line":"    static constexpr auto KIND = NodeKind::CONTINUE_STATEMENT;"},
{"lineNum":"   14","line":""},
{"lineNum":"   15","line":"  public:"},
{"lineNum":"   16","line":"    ContinueStatement(const syntax::Token&                   start_token,"},
{"lineNum":"   17","line":"                      mem::NullableBox<IdentifierExpression> label) noexcept;"},
{"lineNum":"   18","line":"    ~ContinueStatement() override;"},
{"lineNum":"   19","line":""},
{"lineNum":"   20","line":"    MAKE_MOVE_CONSTRUCTABLE_ONLY(ContinueStatement)"},
{"lineNum":"   21","line":""},
{"lineNum":"   22","line":"    auto                      accept(Visitor& v) const noexcept -> void override;"},
{"lineNum":"   23","line":"    [[nodiscard]] static auto parse(syntax::Parser& parser)"},
{"lineNum":"   24","line":"        -> Result<mem::Box<Statement>, syntax::ParserDiagnostic>;"},
{"lineNum":"   25","line":""},
{"lineNum":"   26","line":"    MAKE_NULLABLE_BOX_UNPACKER(label, IdentifierExpression, label_, *)","class":"lineCov","hits":"1","order":"1475",},
{"lineNum":"   27","line":""},
{"lineNum":"   28","line":"  protected:"},
{"lineNum":"   29","line":"    auto is_equal(const Node& other) const noexcept -> bool override;"},
{"lineNum":"   30","line":""},
{"lineNum":"   31","line":"  private:"},
{"lineNum":"   32","line":"    mem::NullableBox<IdentifierExpression> label_;"},
{"lineNum":"   33","line":"};"},
{"lineNum":"   34","line":""},
{"lineNum":"   35","line":"} // namespace porpoise::ast"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2026-04-28 20:58:39", "instrumented" : 1, "covered" : 1,};
var merged_data = [];
