var data = {lines:[
{"lineNum":"    1","line":"#include \"ast/statements/declaration.hpp\""},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include \"ast/expressions/function.hpp\""},
{"lineNum":"    4","line":"#include \"ast/expressions/identifier.hpp\""},
{"lineNum":"    5","line":"#include \"ast/expressions/type.hpp\""},
{"lineNum":"    6","line":"#include \"ast/visitor.hpp\""},
{"lineNum":"    7","line":""},
{"lineNum":"    8","line":"namespace porpoise::ast {"},
{"lineNum":"    9","line":""},
{"lineNum":"   10","line":"DeclStatement::DeclStatement(const syntax::Token&           start_token,"},
{"lineNum":"   11","line":"                             mem::Box<IdentifierExpression> ident,"},
{"lineNum":"   12","line":"                             mem::Box<TypeExpression>       type,"},
{"lineNum":"   13","line":"                             mem::NullableBox<Expression>   value,"},
{"lineNum":"   14","line":"                             DeclModifiers                  modifiers) noexcept"},
{"lineNum":"   15","line":"    : StmtBase{start_token}, ident_{std::move(ident)}, type_{std::move(type)},","class":"lineCov","hits":"1","order":"1515",},
{"lineNum":"   16","line":"      value_{std::move(value)}, modifiers_{modifiers} {}","class":"lineCov","hits":"1","order":"1518",},
{"lineNum":"   17","line":"DeclStatement::~DeclStatement() = default;","class":"lineCov","hits":"1","order":"1512",},
{"lineNum":"   18","line":""},
{"lineNum":"   19","line":"auto DeclStatement::accept(Visitor& v) const -> void { v.visit(*this); }","class":"lineCov","hits":"1","order":"1505",},
{"lineNum":"   20","line":""},
{"lineNum":"   21","line":"auto DeclStatement::parse(syntax::Parser& parser)"},
{"lineNum":"   22","line":"    -> Result<mem::Box<Statement>, syntax::ParserDiagnostic> {","class":"lineCov","hits":"1","order":"1508",},
{"lineNum":"   23","line":"    const auto start_token = parser.get_current_token();","class":"lineCov","hits":"1","order":"1503",},
{"lineNum":"   24","line":"    auto       modifiers   = token_to_modifier(start_token).value();","class":"lineCov","hits":"1","order":"1500",},
{"lineNum":"   25","line":""},
{"lineNum":"   26","line":"    opt::Option<DeclModifiers> current_modifier;","class":"lineCov","hits":"1","order":"1513",},
{"lineNum":"   27","line":"    while ((current_modifier = token_to_modifier(parser.get_peek_token()))) {","class":"lineCov","hits":"1","order":"1516",},
{"lineNum":"   28","line":"        parser.advance();","class":"lineCov","hits":"1","order":"1510",},
{"lineNum":"   29","line":"        if (modifiers_has(modifiers, *current_modifier)) {","class":"lineCov","hits":"1","order":"1498",},
{"lineNum":"   30","line":"            return make_parser_err(syntax::ParserError::DUPLICATE_DECL_MODIFIER, start_token);","class":"lineNoCov","hits":"0",},
{"lineNum":"   31","line":"        }"},
{"lineNum":"   32","line":"        modifiers |= *current_modifier;","class":"lineCov","hits":"1","order":"1495",},
{"lineNum":"   33","line":"    }"},
{"lineNum":"   34","line":""},
{"lineNum":"   35","line":"    if (!validate_modifiers(modifiers)) {","class":"lineCov","hits":"1","order":"1494",},
{"lineNum":"   36","line":"        return make_parser_err(syntax::ParserError::ILLEGAL_DECL_MODIFIERS, start_token);","class":"lineCov","hits":"1","order":"1493",},
{"lineNum":"   37","line":"    }"},
{"lineNum":"   38","line":""},
{"lineNum":"   39","line":"    TRY(parser.expect_peek(syntax::TokenType::IDENT));","class":"lineCov","hits":"1","order":"1517",},
{"lineNum":"   40","line":"    auto decl_name = downcast<IdentifierExpression>(TRY(IdentifierExpression::parse(parser)));","class":"lineCov","hits":"1","order":"1511",},
{"lineNum":"   41","line":"    auto [decl_type, value_initialized] = TRY(TypeExpression::parse(parser));","class":"lineCov","hits":"1","order":"1490",},
{"lineNum":"   42","line":"    auto decl_type_expr                 = downcast<TypeExpression>(std::move(decl_type));","class":"lineCov","hits":"1","order":"1504",},
{"lineNum":"   43","line":""},
{"lineNum":"   44","line":"    mem::NullableBox<Expression> decl_value;","class":"lineCov","hits":"1","order":"1491",},
{"lineNum":"   45","line":"    if (value_initialized) {","class":"lineCov","hits":"1","order":"1506",},
{"lineNum":"   46","line":"        decl_value = mem::nullable_box_from(TRY(parser.parse_expression()));","class":"lineCov","hits":"1","order":"1501",},
{"lineNum":"   47","line":""},
{"lineNum":"   48","line":"        // If there is a value, then there cannot be an extern keyword"},
{"lineNum":"   49","line":"        if (modifiers_has(modifiers, DeclModifiers::EXTERN)) {","class":"lineCov","hits":"1","order":"1489",},
{"lineNum":"   50","line":"            return make_parser_err(syntax::ParserError::EXTERN_VALUE_INITIALIZED, start_token);","class":"lineCov","hits":"1","order":"1488",},
{"lineNum":"   51","line":"        }"},
{"lineNum":"   52","line":"    } else if ((modifiers_has(modifiers, DeclModifiers::CONSTANT) &&","class":"lineCov","hits":"1","order":"1487",},
{"lineNum":"   53","line":"                !modifiers_has(modifiers, DeclModifiers::EXTERN)) ||","class":"lineCov","hits":"1","order":"1486",},
{"lineNum":"   54","line":"               modifiers_has(modifiers, DeclModifiers::CONSTEXPR)) {","class":"lineCov","hits":"1","order":"1485",},
{"lineNum":"   55","line":"        // Constant decls must be declared with a value unless they are extern"},
{"lineNum":"   56","line":"        return make_parser_err(syntax::ParserError::CONST_DECL_MISSING_VALUE, start_token);","class":"lineCov","hits":"1","order":"1484",},
{"lineNum":"   57","line":"    }"},
{"lineNum":"   58","line":""},
{"lineNum":"   59","line":"    if (!parser.current_token_is(syntax::TokenType::SEMICOLON)) {","class":"lineCov","hits":"1","order":"1483",},
{"lineNum":"   60","line":"        TRY(parser.expect_peek(syntax::TokenType::SEMICOLON));","class":"lineCov","hits":"1","order":"1482",},
{"lineNum":"   61","line":"    }","class":"lineCov","hits":"1","order":"1481",},
{"lineNum":"   62","line":"    return mem::make_box<DeclStatement>(start_token,","class":"lineCov","hits":"1","order":"1514",},
{"lineNum":"   63","line":"                                        std::move(decl_name),"},
{"lineNum":"   64","line":"                                        std::move(decl_type_expr),"},
{"lineNum":"   65","line":"                                        std::move(decl_value),"},
{"lineNum":"   66","line":"                                        modifiers);"},
{"lineNum":"   67","line":"}","class":"lineCov","hits":"1","order":"1492",},
{"lineNum":"   68","line":""},
{"lineNum":"   69","line":"auto DeclStatement::is_equal(const Node& other) const noexcept -> bool {","class":"lineCov","hits":"1","order":"1507",},
{"lineNum":"   70","line":"    const auto& casted = as<DeclStatement>(other);","class":"lineCov","hits":"1","order":"1502",},
{"lineNum":"   71","line":"    return *ident_ == *casted.ident_ && *type_ == *casted.type_ &&","class":"lineCov","hits":"1","order":"1499",},
{"lineNum":"   72","line":"           mem::nullable_boxes_eq(value_, casted.value_) && modifiers_ == casted.modifiers_;","class":"lineCov","hits":"1","order":"1480",},
{"lineNum":"   73","line":"}"},
{"lineNum":"   74","line":""},
{"lineNum":"   75","line":"auto validate_non_struct_member(const DeclStatement& decl) noexcept -> bool {","class":"lineCov","hits":"1","order":"1509",},
{"lineNum":"   76","line":"    if (decl.get_value().is<ast::FunctionExpression>()) { return true; }","class":"lineCov","hits":"1","order":"1497",},
{"lineNum":"   77","line":"    return decl.has_modifier(DeclModifiers::STATIC);","class":"lineCov","hits":"1","order":"1496",},
{"lineNum":"   78","line":"}","class":"lineCov","hits":"1","order":"1479",},
{"lineNum":"   79","line":""},
{"lineNum":"   80","line":"} // namespace porpoise::ast"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2026-04-28 20:58:39", "instrumented" : 41, "covered" : 40,};
var merged_data = [];
