var data = {lines:[
{"lineNum":"    1","line":"#include \"ast/statements/discard.hpp\""},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include \"ast/visitor.hpp\""},
{"lineNum":"    4","line":""},
{"lineNum":"    5","line":"namespace porpoise::ast {"},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"auto DiscardStatement::accept(Visitor& v) const -> void { v.visit(*this); }","class":"lineCov","hits":"1","order":"3425",},
{"lineNum":"    8","line":""},
{"lineNum":"    9","line":"auto DiscardStatement::parse(syntax::Parser& parser)"},
{"lineNum":"   10","line":"    -> Result<mem::Box<Statement>, syntax::ParserDiagnostic> {","class":"lineCov","hits":"1","order":"3424",},
{"lineNum":"   11","line":"    const auto start_token = parser.get_current_token();","class":"lineCov","hits":"1","order":"3422",},
{"lineNum":"   12","line":""},
{"lineNum":"   13","line":"    TRY(parser.expect_peek(syntax::TokenType::ASSIGN));","class":"lineCov","hits":"1","order":"3421",},
{"lineNum":"   14","line":"    if (parser.peek_token_is(syntax::TokenType::END) ||","class":"lineCov","hits":"1","order":"3420",},
{"lineNum":"   15","line":"        parser.peek_token_is(syntax::TokenType::SEMICOLON)) {","class":"lineCov","hits":"1","order":"3419",},
{"lineNum":"   16","line":"        return make_parser_err(syntax::ParserError::DISCARD_MISSING_DISCARDEE,","class":"lineCov","hits":"1","order":"3418",},
{"lineNum":"   17","line":"                               parser.get_current_token());","class":"lineCov","hits":"1","order":"3416",},
{"lineNum":"   18","line":"    }"},
{"lineNum":"   19","line":""},
{"lineNum":"   20","line":"    parser.advance();","class":"lineCov","hits":"1","order":"3415",},
{"lineNum":"   21","line":"    auto expr = TRY(parser.parse_expression());","class":"lineCov","hits":"1","order":"3423",},
{"lineNum":"   22","line":""},
{"lineNum":"   23","line":"    if (!parser.current_token_is(syntax::TokenType::SEMICOLON)) {","class":"lineCov","hits":"1","order":"3414",},
{"lineNum":"   24","line":"        TRY(parser.expect_peek(syntax::TokenType::SEMICOLON));","class":"lineCov","hits":"1","order":"3413",},
{"lineNum":"   25","line":"    }","class":"lineCov","hits":"1","order":"3412",},
{"lineNum":"   26","line":"    return mem::make_box<DiscardStatement>(start_token, std::move(expr));","class":"lineCov","hits":"1","order":"3411",},
{"lineNum":"   27","line":"}","class":"lineCov","hits":"1","order":"3417",},
{"lineNum":"   28","line":""},
{"lineNum":"   29","line":"} // namespace porpoise::ast"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2026-04-28 20:58:39", "instrumented" : 15, "covered" : 15,};
var merged_data = [];
