var data = {lines:[
{"lineNum":"    1","line":"#include <algorithm>"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include \"ast/expressions/initializer.hpp\""},
{"lineNum":"    4","line":""},
{"lineNum":"    5","line":"#include \"ast/expressions/prefix.hpp\""},
{"lineNum":"    6","line":"#include \"ast/visitor.hpp\""},
{"lineNum":"    7","line":""},
{"lineNum":"    8","line":"namespace porpoise::ast {"},
{"lineNum":"    9","line":""},
{"lineNum":"   10","line":"Initializer::Initializer(mem::Box<ImplicitAccessExpression> member,"},
{"lineNum":"   11","line":"                         mem::Box<Expression>               value) noexcept"},
{"lineNum":"   12","line":"    : member_{std::move(member)}, value_{std::move(value)} {}","class":"lineCov","hits":"1","order":"1012",},
{"lineNum":"   13","line":"Initializer::~Initializer() = default;","class":"lineCov","hits":"1","order":"1005",},
{"lineNum":"   14","line":""},
{"lineNum":"   15","line":"auto Initializer::accept(Visitor& v) const -> void { v.visit(*this); }","class":"lineCov","hits":"1","order":"999",},
{"lineNum":"   16","line":""},
{"lineNum":"   17","line":"auto Initializer::is_equal(const Initializer& other) const noexcept -> bool {","class":"lineCov","hits":"1","order":"1009",},
{"lineNum":"   18","line":"    return *member_ == *other.member_ && *value_ == *other.value_;","class":"lineCov","hits":"1","order":"1001",},
{"lineNum":"   19","line":"}"},
{"lineNum":"   20","line":""},
{"lineNum":"   21","line":"InitializerExpression::InitializerExpression(const syntax::Token&         start_token,"},
{"lineNum":"   22","line":"                                             mem::NullableBox<Expression> object_type,"},
{"lineNum":"   23","line":"                                             std::vector<Initializer>     initializers) noexcept"},
{"lineNum":"   24","line":"    : ExprBase{start_token}, object_type_{std::move(object_type)},","class":"lineCov","hits":"1","order":"1003",},
{"lineNum":"   25","line":"      initializers_{std::move(initializers)} {}","class":"lineCov","hits":"1","order":"995",},
{"lineNum":"   26","line":"InitializerExpression::~InitializerExpression() = default;","class":"lineCov","hits":"1","order":"996",},
{"lineNum":"   27","line":""},
{"lineNum":"   28","line":"auto InitializerExpression::accept(Visitor& v) const -> void { v.visit(*this); }","class":"lineCov","hits":"1","order":"1006",},
{"lineNum":"   29","line":""},
{"lineNum":"   30","line":"auto InitializerExpression::parse_opt_object(syntax::Parser&              parser,"},
{"lineNum":"   31","line":"                                             mem::NullableBox<Expression> object_type)"},
{"lineNum":"   32","line":"    -> Result<mem::Box<Expression>, syntax::ParserDiagnostic> {","class":"lineCov","hits":"1","order":"993",},
{"lineNum":"   33","line":"    const auto start_token = object_type ? object_type->get_token() : parser.get_current_token();","class":"lineCov","hits":"1","order":"991",},
{"lineNum":"   34","line":""},
{"lineNum":"   35","line":"    std::vector<Initializer> initializers;","class":"lineCov","hits":"1","order":"1010",},
{"lineNum":"   36","line":"    while (!parser.peek_token_is(syntax::TokenType::RBRACE) &&","class":"lineCov","hits":"1","order":"1004",},
{"lineNum":"   37","line":"           !parser.peek_token_is(syntax::TokenType::END)) {","class":"lineCov","hits":"1","order":"990",},
{"lineNum":"   38","line":"        TRY(parser.expect_peek(syntax::TokenType::DOT));","class":"lineCov","hits":"1","order":"997",},
{"lineNum":"   39","line":"        auto member ="},
{"lineNum":"   40","line":"            downcast<ImplicitAccessExpression>(TRY(ImplicitAccessExpression::parse(parser)));","class":"lineCov","hits":"1","order":"1007",},
{"lineNum":"   41","line":""},
{"lineNum":"   42","line":"        TRY(parser.expect_peek(syntax::TokenType::ASSIGN));","class":"lineCov","hits":"1","order":"989",},
{"lineNum":"   43","line":"        parser.advance();","class":"lineCov","hits":"1","order":"988",},
{"lineNum":"   44","line":"        auto value = TRY(parser.parse_expression());","class":"lineCov","hits":"1","order":"987",},
{"lineNum":"   45","line":"        initializers.emplace_back(std::move(member), std::move(value));","class":"lineCov","hits":"1","order":"986",},
{"lineNum":"   46","line":""},
{"lineNum":"   47","line":"        if (!parser.peek_token_is(syntax::TokenType::RBRACE)) {","class":"lineCov","hits":"1","order":"1002",},
{"lineNum":"   48","line":"            TRY(parser.expect_peek(syntax::TokenType::COMMA));","class":"lineCov","hits":"1","order":"994",},
{"lineNum":"   49","line":"        }","class":"lineCov","hits":"1","order":"985",},
{"lineNum":"   50","line":"    }","class":"lineCov","hits":"1","order":"984",},
{"lineNum":"   51","line":"    TRY(parser.expect_peek(syntax::TokenType::RBRACE));","class":"lineCov","hits":"1","order":"983",},
{"lineNum":"   52","line":""},
{"lineNum":"   53","line":"    return mem::make_box<InitializerExpression>(","class":"lineCov","hits":"1","order":"982",},
{"lineNum":"   54","line":"        start_token, std::move(object_type), std::move(initializers));"},
{"lineNum":"   55","line":"}","class":"lineCov","hits":"1","order":"992",},
{"lineNum":"   56","line":""},
{"lineNum":"   57","line":"auto InitializerExpression::parse(syntax::Parser& parser, mem::Box<Expression> object_type)"},
{"lineNum":"   58","line":"    -> Result<mem::Box<Expression>, syntax::ParserDiagnostic> {","class":"lineCov","hits":"1","order":"981",},
{"lineNum":"   59","line":"    return parse_opt_object(parser, mem::NullableBox<Expression>{object_type.release()});","class":"lineCov","hits":"1","order":"1011",},
{"lineNum":"   60","line":"}","class":"lineNoCov","hits":"0",},
{"lineNum":"   61","line":""},
{"lineNum":"   62","line":"auto InitializerExpression::is_equal(const Node& other) const noexcept -> bool {","class":"lineCov","hits":"1","order":"998",},
{"lineNum":"   63","line":"    const auto& casted = as<InitializerExpression>(other);","class":"lineCov","hits":"1","order":"980",},
{"lineNum":"   64","line":"    return mem::nullable_boxes_eq(object_type_, casted.object_type_) &&","class":"lineCov","hits":"1","order":"1008",},
{"lineNum":"   65","line":"           std::ranges::equal(initializers_, casted.initializers_);","class":"lineCov","hits":"1","order":"1000",},
{"lineNum":"   66","line":"}"},
{"lineNum":"   67","line":""},
{"lineNum":"   68","line":"} // namespace porpoise::ast"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2026-04-28 20:58:39", "instrumented" : 34, "covered" : 33,};
var merged_data = [];
