var data = {lines:[
{"lineNum":"    1","line":"#include <fmt/format.h>"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include \"sema/module/module.hpp\""},
{"lineNum":"    4","line":""},
{"lineNum":"    5","line":"namespace porpoise::sema::mod {"},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"auto Module::print_diagnostics(std::ostream& os) const -> void {","class":"lineNoCov","hits":"0",},
{"lineNum":"    8","line":"    if (!is_errored()) { return; }","class":"lineNoCov","hits":"0",},
{"lineNum":"    9","line":"    match([&](const auto& l) { l.print(os, *this); });","class":"lineNoCov","hits":"0",},
{"lineNum":"   10","line":"}","class":"lineNoCov","hits":"0",},
{"lineNum":"   11","line":""},
{"lineNum":"   12","line":"auto ModuleManager::try_get_file_module(const std::filesystem::path& path,"},
{"lineNum":"   13","line":"                                        const std::filesystem::path& parent_path)"},
{"lineNum":"   14","line":"    -> Result<mem::NonNull<Module>, Diagnostic> {","class":"lineCov","hits":"1","order":"584",},
{"lineNum":"   15","line":"    assert((parent_path.empty() || parent_path.is_absolute()) &&","class":"lineCov","hits":"1","order":"572",},
{"lineNum":"   16","line":"           \"Parent path must be absolute or empty\");"},
{"lineNum":"   17","line":"    if (!path.is_relative()) {","class":"lineCov","hits":"1","order":"583",},
{"lineNum":"   18","line":"        return make_sema_err(fmt::format(\"Requested file \'{}\' is absolute\", path.string()),","class":"lineNoCov","hits":"0",},
{"lineNum":"   19","line":"                             Error::IMPORT_NOT_RELATIVE);","class":"lineNoCov","hits":"0",},
{"lineNum":"   20","line":"    };"},
{"lineNum":"   21","line":""},
{"lineNum":"   22","line":"    const auto normalized = loader_.normalize(parent_path.empty() ? path : parent_path / path);","class":"lineCov","hits":"1","order":"576",},
{"lineNum":"   23","line":"    if (!normalized) { return make_sema_err(normalized.error()); }","class":"lineCov","hits":"1","order":"579",},
{"lineNum":"   24","line":"    return try_get(*normalized);","class":"lineCov","hits":"1","order":"575",},
{"lineNum":"   25","line":"}","class":"lineCov","hits":"1","order":"588",},
{"lineNum":"   26","line":""},
{"lineNum":"   27","line":"auto ModuleManager::try_get_library_module(const std::string& name)"},
{"lineNum":"   28","line":"    -> Result<mem::NonNull<Module>, Diagnostic> {","class":"lineCov","hits":"1","order":"564",},
{"lineNum":"   29","line":"    auto it = module_lut_.find(name);","class":"lineCov","hits":"1","order":"568",},
{"lineNum":"   30","line":"    if (it == module_lut_.end()) {","class":"lineCov","hits":"1","order":"566",},
{"lineNum":"   31","line":"        return make_sema_err(fmt::format(\"Unknown module \'{}\'\", name),","class":"lineNoCov","hits":"0",},
{"lineNum":"   32","line":"                             Error::MODULE_DOES_NOT_EXIST);","class":"lineNoCov","hits":"0",},
{"lineNum":"   33","line":"    }"},
{"lineNum":"   34","line":"    return try_get(it->second);","class":"lineCov","hits":"1","order":"562",},
{"lineNum":"   35","line":"}","class":"lineCov","hits":"1","order":"563",},
{"lineNum":"   36","line":""},
{"lineNum":"   37","line":"auto ModuleManager::add_porpoise_module(const std::string& name, const std::filesystem::path& path)"},
{"lineNum":"   38","line":"    -> Result<Unit, Diagnostic> {","class":"lineCov","hits":"1","order":"561",},
{"lineNum":"   39","line":"    const auto normalized = loader_.normalize(path);","class":"lineCov","hits":"1","order":"560",},
{"lineNum":"   40","line":"    if (!normalized) { return make_sema_err(normalized.error()); }","class":"lineCov","hits":"1","order":"559",},
{"lineNum":"   41","line":""},
{"lineNum":"   42","line":"    if (auto it = module_lut_.find(name); it != module_lut_.end()) {","class":"lineCov","hits":"1","order":"558",},
{"lineNum":"   43","line":"        if (it->second == normalized) { return Unit{}; }","class":"lineNoCov","hits":"0",},
{"lineNum":"   44","line":"        return make_sema_err(","class":"lineNoCov","hits":"0",},
{"lineNum":"   45","line":"            fmt::format(","class":"lineNoCov","hits":"0",},
{"lineNum":"   46","line":"                \"Attempt to add duplicate module {} from {} which already exists at path {}\",","class":"lineNoCov","hits":"0",},
{"lineNum":"   47","line":"                name,","class":"lineNoCov","hits":"0",},
{"lineNum":"   48","line":"                normalized->string(),","class":"lineNoCov","hits":"0",},
{"lineNum":"   49","line":"                it->second.string()),","class":"lineNoCov","hits":"0",},
{"lineNum":"   50","line":"            Error::MODULE_ALREADY_EXISTS);","class":"lineNoCov","hits":"0",},
{"lineNum":"   51","line":"    }"},
{"lineNum":"   52","line":""},
{"lineNum":"   53","line":"    module_lut_.emplace(name, *normalized);","class":"lineCov","hits":"1","order":"557",},
{"lineNum":"   54","line":"    return Unit{};","class":"lineCov","hits":"1","order":"556",},
{"lineNum":"   55","line":"}","class":"lineCov","hits":"1","order":"591",},
{"lineNum":"   56","line":""},
{"lineNum":"   57","line":"auto ModuleManager::try_get(const std::filesystem::path& path)"},
{"lineNum":"   58","line":"    -> Result<mem::NonNull<Module>, Diagnostic> {","class":"lineCov","hits":"1","order":"574",},
{"lineNum":"   59","line":"    // Prevent re-parsing by checking the map, safe as pointers are stable"},
{"lineNum":"   60","line":"    if (auto it = modules_.find(path); it != modules_.end()) { return it->second.get(); }","class":"lineCov","hits":"1","order":"589",},
{"lineNum":"   61","line":"    auto       source       = loader_.load(path);","class":"lineCov","hits":"1","order":"585",},
{"lineNum":"   62","line":"    const auto abs_path_str = path.string();","class":"lineCov","hits":"1","order":"573",},
{"lineNum":"   63","line":"    if (!source) {","class":"lineCov","hits":"1","order":"581",},
{"lineNum":"   64","line":"        return make_sema_err(fmt::format(R\"(Could not load file: \"{}\")\", abs_path_str),","class":"lineCov","hits":"1","order":"582",},
{"lineNum":"   65","line":"                             source.error());","class":"lineCov","hits":"1","order":"590",},
{"lineNum":"   66","line":"    }"},
{"lineNum":"   67","line":""},
{"lineNum":"   68","line":"    auto mod = mem::make_box<Module>(path, path.parent_path(), SourceFile{std::move(*source)});","class":"lineCov","hits":"1","order":"580",},
{"lineNum":"   69","line":"    syntax::Parser p{mod->source};","class":"lineCov","hits":"1","order":"577",},
{"lineNum":"   70","line":"    auto [ast, diagnostics] = p.consume();","class":"lineCov","hits":"1","order":"578",},
{"lineNum":"   71","line":""},
{"lineNum":"   72","line":"    mod->tree        = std::move(ast);","class":"lineCov","hits":"1","order":"587",},
{"lineNum":"   73","line":"    mod->state       = diagnostics.empty() ? ModuleState::PARSED : ModuleState::ERRORED;","class":"lineCov","hits":"1","order":"571",},
{"lineNum":"   74","line":"    mod->diagnostics = std::move(diagnostics);","class":"lineCov","hits":"1","order":"570",},
{"lineNum":"   75","line":""},
{"lineNum":"   76","line":"    auto* ptr = mod.get();","class":"lineCov","hits":"1","order":"569",},
{"lineNum":"   77","line":"    modules_.emplace(path, std::move(mod));","class":"lineCov","hits":"1","order":"567",},
{"lineNum":"   78","line":"    return ptr;","class":"lineCov","hits":"1","order":"565",},
{"lineNum":"   79","line":"}","class":"lineCov","hits":"1","order":"586",},
{"lineNum":"   80","line":""},
{"lineNum":"   81","line":"} // namespace porpoise::sema::mod"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2026-04-28 20:58:39", "instrumented" : 52, "covered" : 36,};
var merged_data = [];
