#pragma once

#include "diagnostic.hh"
#include "result.hh"
#include "types.hh"

namespace porpoise::syntax {

enum class Error : u8 {
    UNEXPECTED_TOKEN,
    MISSING_PREFIX_PARSER,
    INFIX_MISSING_RHS,
    ILLEGAL_IDENTIFIER,
    END_OF_TOKEN_STREAM,
    CONST_DECL_MISSING_VALUE,
    EMPTY_FILE_IMPORT,
    ILLEGAL_IMPORT_TYPE,
    FILE_IMPORT_MISSING_ALIAS,
    DUPLICATE_DECL_MODIFIER,
    ILLEGAL_DECL_MODIFIERS,
    INTEGER_OVERFLOW,
    FLOAT_OVERFLOW,
    DOUBLE_OVERFLOW,
    UNKNOWN_CHARACTER_ESCAPE,
    PREFIX_MISSING_OPERAND,
    INDEX_MISSING_EXPRESSION,
    ILLEGAL_IMPLICIT_ACCESS_OPERAND,
    DISCARD_MISSING_DISCARDEE,
    EMPTY_LOOP,
    WHILE_MISSING_CONDITION,
    INVALID_MEMBER,
    EXTERN_VALUE_INITIALIZED,
    ILLEGAL_LOOP_NON_BREAK,
    FOR_MISSING_ITERABLES,
    FOR_ITERABLE_CAPTURE_MISMATCH,
    EMPTY_WHILE_CONTINUATION,
    IF_MISSING_CONDITION,
    ILLEGAL_IF_BRANCH,
    MISSING_ARRAY_SIZE_TOKEN,
    MATCH_EXPR_MISSING_CONDITION,
    ARMLESS_MATCH_EXPR,
    ILLEGAL_MATCH_ARM,
    ILLEGAL_MATCH_CATCH_ALL,
    FN_PARAMETER_HAS_DEFAULT_VALUE,
    FN_PARAMETER_IS_NORETURN,
    ILLEGAL_EXPLICIT_TYPE,
    MISSING_EXPLICIT_TYPE,
    EXPLICIT_FN_TYPE_HAS_BODY,
    FN_DECLARATION_WITHOUT_BODY,
    ILLEGAL_OUTER_SCOPE_TYPE,
    ILLEGAL_FUNCTION_TYPE_MODIFIER,
    ILLEGAL_NORETURN_TYPE_MODIFIER,
    ILLEGAL_VOID_TYPE_MODIFIER,
    ILLEGAL_TYPE_TYPE_MODIFIER,
    COMMA_WITH_MISSING_CALL_ARGUMENT,
    EMPTY_UNION,
    EMPTY_ENUM,
    ILLEGAL_DEFERRED_STATEMENT,
    DEFER_MISSING_DEFERREE,
    EMPTY_TEST_DESCRIPTION,
    VALUED_BREAK_MISSING_LABEL,
    VALUED_CONTINUE,
    ILLEGAL_LABEL,
    ILLEGAL_LABEL_EXPRESSION,
    ILLEGAL_LABEL_STATEMENT,
    UNDEFINED_DECL_MISSING_TYPE,
};

using Diagnostic  = Diagnostic<Error>;
using Diagnostics = DiagnosticList<Diagnostic>;

template <typename... Args>
[[nodiscard]] constexpr auto make_syntax_err(Args&&... args) -> Err<Diagnostic> {
    return make_err<Diagnostic>(std::forward<Args>(args)...);
}

} // namespace porpoise::syntax
