//! https://github.com/llvm/llvm-project/blob/llvmorg-21.1.8/llvm/lib/IR/CMakeLists.txt
const LLVMBuilder = @import("../../LLVMBuilder.zig");
const SynthesizeHeaderConfig = LLVMBuilder.SynthesizeHeaderConfig;

pub const root = "llvm/lib/IR";
pub const sources = [_][]const u8{
    "AbstractCallSite.cpp",
    "AsmWriter.cpp",
    "Assumptions.cpp",
    "Attributes.cpp",
    "AutoUpgrade.cpp",
    "BasicBlock.cpp",
    "BuiltinGCs.cpp",
    "Comdat.cpp",
    "ConstantFold.cpp",
    "ConstantFPRange.cpp",
    "ConstantRange.cpp",
    "ConstantRangeList.cpp",
    "Constants.cpp",
    "ConvergenceVerifier.cpp",
    "Core.cpp",
    "CycleInfo.cpp",
    "DIBuilder.cpp",
    "DataLayout.cpp",
    "DebugInfo.cpp",
    "DebugInfoMetadata.cpp",
    "DIExpressionOptimizer.cpp",
    "DebugProgramInstruction.cpp",
    "DebugLoc.cpp",
    "DiagnosticHandler.cpp",
    "DiagnosticInfo.cpp",
    "DiagnosticPrinter.cpp",
    "Dominators.cpp",
    "DroppedVariableStats.cpp",
    "DroppedVariableStatsIR.cpp",
    "EHPersonalities.cpp",
    "FPEnv.cpp",
    "Function.cpp",
    "GCStrategy.cpp",
    "GVMaterializer.cpp",
    "Globals.cpp",
    "Intrinsics.cpp",
    "IRBuilder.cpp",
    "IRPrintingPasses.cpp",
    "SSAContext.cpp",
    "InlineAsm.cpp",
    "Instruction.cpp",
    "Instructions.cpp",
    "IntrinsicInst.cpp",
    "LLVMContext.cpp",
    "LLVMContextImpl.cpp",
    "LLVMRemarkStreamer.cpp",
    "LegacyPassManager.cpp",
    "MDBuilder.cpp",
    "MemoryModelRelaxationAnnotations.cpp",
    "Mangler.cpp",
    "Metadata.cpp",
    "Module.cpp",
    "ModuleSummaryIndex.cpp",
    "Operator.cpp",
    "OptBisect.cpp",
    "Pass.cpp",
    "PassInstrumentation.cpp",
    "PassManager.cpp",
    "PassRegistry.cpp",
    "PassTimingInfo.cpp",
    "PrintPasses.cpp",
    "ProfDataUtils.cpp",
    "SafepointIRVerifier.cpp",
    "ProfileSummary.cpp",
    "PseudoProbe.cpp",
    "ReplaceConstant.cpp",
    "Statepoint.cpp",
    "StructuralHash.cpp",
    "Type.cpp",
    "TypedPointerType.cpp",
    "TypeFinder.cpp",
    "Use.cpp",
    "User.cpp",
    "Value.cpp",
    "ValueSymbolTable.cpp",
    "VectorTypeUtils.cpp",
    "Verifier.cpp",
    "VFABIDemangler.cpp",
    "RuntimeLibcalls.cpp",
};

const include_root = "llvm/include/llvm/IR/";
pub const synthesize_configs = [_]SynthesizeHeaderConfig{
    .{
        .gen_conf = .{
            .name = "Attributes",
            .td_file = include_root ++ "Attributes.td",
            .instruction = .{ .action = "-gen-attrs" },
        },
        .virtual_path = "llvm/IR/Attributes.inc",
    },
    .{
        .gen_conf = .{
            .name = "IntrinsicEnums",
            .td_file = include_root ++ "Intrinsics.td",
            .instruction = .{ .action = "-gen-intrinsic-enums" },
        },
        .virtual_path = "llvm/IR/IntrinsicEnums.inc",
    },
    .{
        .gen_conf = .{
            .name = "RuntimeLibcalls",
            .td_file = include_root ++ "RuntimeLibcalls.td",
            .instruction = .{ .action = "-gen-runtime-libcalls" },
        },
        .virtual_path = "llvm/IR/RuntimeLibcalls.inc",
    },
    .{
        .gen_conf = .{
            .name = "IntrinsicImpl",
            .td_file = include_root ++ "Intrinsics.td",
            .instruction = .{ .action = "-gen-intrinsic-impl" },
        },
        .virtual_path = "llvm/IR/IntrinsicImpl.inc",
    },
};

const Intrinsic = struct {
    arch: []const u8,
    prefix: []const u8,
};

/// https://github.com/llvm/llvm-project/blob/llvmorg-21.1.8/llvm/include/llvm/IR/CMakeLists.txt
pub const intrinsic_info = [_]Intrinsic{
    .{ .arch = "AArch64", .prefix = "aarch64" },     .{ .arch = "AMDGPU", .prefix = "amdgcn" },
    .{ .arch = "ARM", .prefix = "arm" },             .{ .arch = "BPF", .prefix = "bpf" },
    .{ .arch = "DirectX", .prefix = "dx" },          .{ .arch = "Hexagon", .prefix = "hexagon" },
    .{ .arch = "LoongArch", .prefix = "loongarch" }, .{ .arch = "Mips", .prefix = "mips" },
    .{ .arch = "NVPTX", .prefix = "nvvm" },          .{ .arch = "PowerPC", .prefix = "ppc" },
    .{ .arch = "R600", .prefix = "r600" },           .{ .arch = "RISCV", .prefix = "riscv" },
    .{ .arch = "SPIRV", .prefix = "spv" },           .{ .arch = "S390", .prefix = "s390" },
    .{ .arch = "WebAssembly", .prefix = "wasm" },    .{ .arch = "X86", .prefix = "x86" },
    .{ .arch = "XCore", .prefix = "xcore" },         .{ .arch = "VE", .prefix = "ve" },
};
