name: Formatting

on:
    pull_request:
        branches: [main, dev]
        paths:
            - ".github/workflows/format.yml"
            - "lib/**"
            - "porpoise/main.cpp"
            - "third-party/**"
            - "tools/harness/**"
            - "build.zig"
            - "build.zig.zon"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    fmt:
        permissions:
            contents: read
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - uses: mlugg/setup-zig@v2
              with:
                  version: 0.15.2

            - name: Cache Zig Folders
              uses: actions/cache@v4
              with:
                path: |
                  ${{ env.ZIG_LOCAL_CACHE_DIR }}
                  ${{ env.ZIG_GLOBAL_CACHE_DIR }}
                key: ${{ runner.os }}-zig-${{ hashFiles('third-party/llvm/**.zig') }}
                restore-keys: |
                  ${{ runner.os }}-zig-

            - name: Fetch dependencies
              run: |
                  zig build --fetch=all -j2

            - name: Check formatting
              run: zig build fmt-check

            - name: Run static analysis
              run: zig build check
