name: Package Release

on:
    push:
        tags:
            - "v*"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    package:
        permissions:
            contents: write
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - uses: mlugg/setup-zig@v2
              with:
                  version: 0.15.2

            - name: Fetch dependencies
              run: |
                  zig build --fetch=all -j2

            - name: Build and package
              run: zig build package

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: conch-binaries
                  path: |
                      zig-out/package/*.tar.zst
                      zig-out/package/*.zip
                  if-no-files-found: error
